name: Build, Push & Deploy to EC2

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Клонируем репозиторий
      - name: Checkout
        uses: actions/checkout@v4

      # 2️⃣ Логинимся в Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3️⃣ Сборка и пуш образа
      - name: Build & push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest

      # 4️⃣ Деплой на EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu            # SSH пользователь
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          script: |
            set -e
            echo "Pulling latest image..."
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest

            echo "Checking for existing container..."
            EXISTING=$(docker ps -a -q --filter "name=myapp")
            if [ -n "$EXISTING" ]; then
              echo "Killing existing container processes..."
              PID=$(docker inspect --format '{{.State.Pid}}' myapp)
              if [ -n "$PID" ]; then
                sudo kill -9 $PID || true
              fi
              echo "Removing old container..."
              sudo docker rm -f myapp || true
            fi

            echo "Starting new container..."
            docker run -d --name myapp --restart=always -p 8080:80 ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest
