- name: Deploy to EC2
  uses: appleboy/ssh-action@v0.1.10
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ${{ secrets.EC2_USER }}
    key: ${{ secrets.EC2_SSH_KEY }}
    script_stop: true
    script: |
      set -e

      APP_NAME=myapp
      IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest

      echo "📥 Pulling latest image..."
      sudo docker pull $IMAGE

      echo "🛑 Stopping and removing old container if exists..."
      OLD_CID=$(sudo docker ps -aq --filter "name=$APP_NAME")
      if [ -n "$OLD_CID" ]; then
        echo "Removing old container: $OLD_CID"
        sudo docker rm -f $OLD_CID || true
      fi

      echo "🧹 Cleaning unused Docker resources..."
      sudo docker system prune -af --volumes || true

      echo "🚀 Starting new container..."
      sudo docker run -d \
        --name $APP_NAME \
        --restart=always \
        -p 8080:80 \
        $IMAGE

      echo "📋 Running containers:"
      sudo docker ps -a

      echo "📜 Last logs from $APP_NAME:"
      sudo docker logs --tail=50 $APP_NAME || true
