name: Build, Push & Deploy to EC2

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest

      - uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          script: |
            set -e
            APP=myapp
            IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest
            CID=$(sudo docker ps -aq --filter "name=$APP")
            [ -n "$CID" ] && sudo docker rm -f $CID || true
            sudo docker system prune -af --volumes || true
            sudo docker pull $IMAGE
            sudo docker run -d --name $APP --restart=always -p 8080:80 $IMAGE
            sudo docker ps -a
            sudo docker logs --tail=50 $APP || true
